### ISSUE TITLE
NBAI MINING NODE

### ISSUE THREAD

**Issue by enamsuo78** [nebulaai/nbai-node#12]
Hi there,

I tried to connect to the mining node with my computer under window but I did not succeed.

best regards

**Comment by czhang-nbai** [comment]
This client is mainly for connecting to our network, if you want to mine NBAI, please refer to http://aegispool.org
If it's not the answer you expected, don't hesitate to contact us

**Comment by flyworker** [comment]
no I guess this issue is a different one.
@enamsuo78 could you please add the log or screenshot?

**Comment by enamsuo78** [comment]
![photo5956096729122188893](https://user-images.githubusercontent.com/35670336/57551097-7ba95a00-7368-11e9-9105-18003e914835.jpg)

**Comment by enamsuo78** [comment]
that's what you wanted to see?
